public class navatarResearchConstantCtrl {
    public static string handelArributeSpecialChars='\\?&|!{}[]()^~*:+-\'';
    public static string handelArribute2='=###= ,,,';
    public static string handelArribute3=' =###= ';
    public static string handelArribute4='=###=';
    public static string handelArribute5='hp9090hp';
    public static string handelArribute6='\\\\';
    public static string handelArribute7='';
}